spring.application.name=backend

spring.datasource.url=jdbc:h2:file:./storage/movieuniverse
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.h2.console.enabled=true

app.seed.file=../data/seed_playlists.json